#!/bin/bash

# make dir
mkdir Suchkov
git init
git checkout -b rc
python3 -c "import hhgit; hhgit.to_text(['img/init.png'],'Suchkov/main.txt')"
git add Suchkov/main.txt
git commit -m"init [init.png] -> main.txt"

git checkout -b bugfix
python3 -c "import hhgit; hhgit.to_text(['img/bugfix.png','img/init.png'],'Suchkov/main.txt')"
git add Suchkov/main.txt
git commit -m"bugfix [init.png bugfix.png] -> main.txt"

git checkout rc
git checkout -b feature1
python3 -c "import hhgit; hhgit.to_text(['img/refactoring.png','img/init.png'],'Suchkov/main.txt')"
git add Suchkov/main.txt
git commit -m"feature1 [refactoring.png init.png] -> main.txt"

git checkout -b feature2
python3 -c "import hhgit; hhgit.to_text(['img/refactoring.png','img/init.png','img/feature2.png'],'Suchkov/main.txt')"
git add Suchkov/main.txt
git commit -m"feature2 [refactoring.png init.png feature2.png] -> main.txt"

git checkout feature1
git checkout -b feature1-refactoring
python3 -c "import hhgit; hhgit.to_text(['img/init.png'],'Suchkov/main.txt')"
python3 -c "import hhgit; hhgit.to_text(['img/refactoring.png'],'Suchkov/refactoring.txt')"
git add Suchkov/main.txt
git add Suchkov/refactoring.txt
git commit -m"feature2 [init.png feature1.png] -> main.txt"

git checkout rc
git merge bugfix --no-edit
git merge feature1-refactoring --no-edit
git merge feature2 --no-edit


